name: py36_egm
channels:
  - pytorch
  - defaults
dependencies:
  - cudatoolkit=11.0.221
  - jupyterlab=2.2.6
  - matplotlib=3.3.2
  - notebook=6.1.6
  - numpy=1.19.2
  - pandas=1.1.3
  - pip=20.3.3
  - python=3.6.12
  - pytorch=1.7.1
  - scikit-learn=0.23.2
  - scipy=1.5.2
  - tqdm=4.55.1
  - pip:
    - tensorflow-gpu==1.15.0
